"use strict";
// Definitions in this file would be auto-generated by `graph codegen`
exports.__esModule = true;
exports.BlockEntity = void 0;
var BlockEntity = /** @class */ (function () {
    function BlockEntity() {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        Object.assign(this, args);
    }
    return BlockEntity;
}());
exports.BlockEntity = BlockEntity;
