
import { graphql, BlockEvent, store, log, TransactionEvent, Network } from "../../graph";

/***
 * Generated
 * Definitions here would be auto-generated by `graph codegen`
 */
 class TransactionEntity {
  height: number;
  hash: string;
  time: Date;
  myNote: string;

  constructor(args) {
    Object.assign(this, args);
  }

  save() {
    return store.save("Transaction", this);
  }
}

 class BlockEntity {
   height: number;
   hash: string;
   time: Date;
   myNote: string;
   transactions: TransactionEntity[];

  constructor(args) {
    Object.assign(this, args);
  }

  save() {
    return store.save("Block", this);
  }
}

/**
 * Mapping
 */
const GET_BLOCK = `query GetBlock($height: Int = 0, $chain_id: String = "mainnet") {
  block( height: $height, chain_id: $chain_id) {
    hash
    height
    time
  }
}`;

/**
 * This function is defined in the subgraph.yaml.
 *
 * Ex:
 * ```yaml
 * # ...
 * mapping:
 *  kind: cosmos/blocks
 *  apiVersion: 0.0.1
 *  language: wasm/assemblyscript
 *  transactionHandlers:
 *    - function: handleTransaction
 *  blockHandlers:
 *    - function: handleBlock
 * ```
 */
function handleBlock(newBlockEvent: BlockEvent) {
  log.debug('newBlockEvent: ' + JSON.stringify(newBlockEvent));

  const {error, data} = graphql.call("cosmos" as Network, GET_BLOCK, { height: newBlockEvent.height, chain_id: "cosmoshub-4" }, "0.0.1");

  if (error) {
    log.debug('GQL call error: ' + JSON.stringify(error));
    return;
  }

  if (!data) {
    log.debug('GQL call returned no data');
    return;
  }

  log.debug('GQL call data: ' + JSON.stringify(data));

  const entity = new BlockEntity({ hash: data.block.hash,height: data.block.height, myNote: "some additional data", time: data.block.time });

  log.debug('Entity: ' + JSON.stringify(entity));

  const storeErr = entity.save();
  if (storeErr !== undefined) {
    log.debug('Error storing block: ' + JSON.stringify(storeErr));
  } else {
    log.debug('Block stored: ' + JSON.stringify(newBlockEvent));
  }
}

var GET_TRANSACTIONS = `query GetTransactions($hash: String, $chain_id: String = "mainnet") {
  transaction(hash: $hash, chain_id: $chain_id) {
    hash
    height
    time
  }
}`;

function handleTransaction(newTxnEvent: TransactionEvent) {

  log.debug('newTxnEvent: ' + JSON.stringify(newTxnEvent));

  const {error, data} = graphql.call("cosmos" as Network, GET_TRANSACTIONS, { hash: newTxnEvent.hash, chain_id: "cosmoshub-4" }, "0.0.1");

  if (error) {
    log.debug('GQL call error: ' + JSON.stringify(error));
    return;
  }

  if (!data) {
    log.debug('GQL call returned no data');
    return;
  }

  log.debug('GQL call data: ' + JSON.stringify(data));

  const tx = data.transaction[0];
  const entity = new TransactionEntity({ hash: tx.hash, height: tx.height, myNote: "some additional data", time: tx.time });

  log.debug('Entity: ' + JSON.stringify(entity));

  const storeErr = entity.save();
  if (storeErr !== undefined) {
    log.debug('Error storing transaction: ' + JSON.stringify(storeErr));
  } else {
    log.debug('Transaction stored: ' + JSON.stringify(newTxnEvent));
  }
}
