// This test is used by jsRunner_test.go

import { graphql, BlockEvent, store, log } from "../../graph";

/***
 * Generated
 * Entity definitions here would be auto-generated by `graph codegen`
 */
class TransactionEntity {
  save() {
    return store.save("Transaction", this);
  }
}

class BlockEntity {
  id: string;
  height: number;
  time: Date;
  myNote: string;
  transactions: TransactionEntity[];

  constructor(height: number, id: string, time: Date, myNote: string) {
    this.id = id;
    this.height = height;
    this.time = time;
    this.myNote = myNote;
  }

  save() {
    return store.save("Block", this);
  }
}
/**
 * Mapping
 */
const GET_BLOCK = `query GetBlock($height: Int) {
    block( $height: Int = 0 ) {
      height
      time
      id
    }
  }`;

function handleBlock(newBlockEvent: BlockEvent) {
    const { data, error } = graphql.call(newBlockEvent.network, GET_BLOCK, { height: newBlockEvent.height }, "0.0.1");

    if (error) {
      log.debug(JSON.stringify(error));
      return;
    }

    log.debug('data from query: ' + JSON.stringify(data));

    const { height, id, time } = data;
    const entity = new BlockEntity(height, id, time, "ok");

    log.debug('saving: ' + JSON.stringify(entity));

    entity.save();
}
